FROM node:20-alpine AS builder
WORKDIR /app
COPY ../../frontend/package.json ./
COPY ../../frontend/tsconfig.json ./
COPY ../../frontend/vite.config.ts ./
COPY ../../frontend/src ./src
RUN npm install && npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
